name: ci-checks-tf

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  id-token: write
  contents: write
  pull-requests: write


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container: ghcr.io/antonbabenko/pre-commit-terraform:v1.88.4
    steps:
      - uses: actions/checkout@v3

      - name: 'pre-commit::add-github-repo-safe'
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: 'pre-commit::run-all-checks'
        run: |
          pre-commit run -a --show-diff-on-failure -v

  module-required-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'tf-module::check-required-files'
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "variables.tf, main.tf, README.md, versions.tf"
          fail: true

  label-required-semver:
    runs-on: ubuntu-latest
    steps:
      - name: 'pr::check-required-semver'
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          one_of: "release/" # patch , minor , major
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  label-required-pr-type:
    runs-on: ubuntu-latest
    steps:
      - name: 'pr::check-required-pr-type'
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: bug,enhancement,documentation,security
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  label-do-not-merge:
    runs-on: ubuntu-latest
    steps:
      - name: 'pr::check-required-semver'
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          none_of: do-not-merge
          repo_token: ${{ secrets.GITHUB_TOKEN }}
